[router]
# OpenWRT mặc định user là root và chưa có password, có thể để trống hoặc cài pass sau
openwrt ansible_host=192.168.10.1 ansible_user=root ansible_ssh_pass=admin123 ansible_ssh_extra_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no' ansible_python_interpreter=/usr/bin/python3.13

[lan_hosts]
lan-ubuntu ansible_host=192.168.10.100 ansible_user=vagrant ansible_ssh_pass=vagrant ansible_become_pass=vagrant

[guest_hosts]
guest-ubuntu ansible_host=192.168.2.100 ansible_user=vagrant ansible_ssh_pass=vagrant ansible_become_pass=vagrant

[wan_hosts]
wan-attacker ansible_host=192.168.0.10 ansible_user=vagrant ansible_ssh_pass=vagrant ansible_become_pass=vagrant
